---
title: "WordPress Website Setup for goodpress"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{setup}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

To be able to use goodpress to publish posts on your WordPress website, you need to perform a few setup steps. You only need to do these *once*, so that's only potentially painful at setup.

You might not need to tweak syntax highlighting and math stuff if you, well, never show code or never show math equations in your posts.

## Authentication

From WordPress point-of-view this package is a "remote application" therefore it needs your website to use an [authentication _plugin_](https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/#authentication-plugins).
At the moment, for the sake of simplicity, this package only relies on [Application Passwords](https://wordpress.org/plugins/application-passwords/).

You cannot install plugins if you use wordpress.com (unless you have a costly business plan there), therefore with wordpress.com you cannot use the REST API.
There are paid services out there providing a domain name, hosting and a one-click WordPress install, 
for a few dollars a month,
that you could use if you don't roll your own server.

Here's what I did to be able to use this package on my [test website](https://rmd-wordpress.eu/):

* Installed and activated the [Application Passwords plugin](https://wordpress.org/plugins/application-passwords/). _Don't forget to keep your WordPress plugins up-to-date especially because of security updates._
* Created a new user with editor rights, not admin, and from the admin panel I created an application password for "rmarkdown" for that user. _Doing this for an user with restricted access is safer._
* In [`.Renviron`](https://rstats.wtf/r-startup.html#renviron), save username as `WP_USER` and application password as `WP_PWD`. Re-start R. _Keep `.Renviron` safe, it contains secrets!_ Here's an example of .Renviron below, the empty line at the end of the file is needed.

```yaml
WP_PWD="your application password including space e.g. blabla blabla blabla blabla NOT your WordPress main password"
WP_USER="yourusername"

```

* Edited the [.htaccess file of my website](https://github.com/georgestephanis/application-passwords/wiki/Basic-Authorization-Header----Missing).

## Syntax highlighting

### For R

To get syntax highlighting for R blocks, at the moment you need to add custom CSS (once, like the plugin setup stuff).

* Find `system.file(file.path("css", "code.css"), package = "goodpress")` and copy it to your clipboard.
* From your WordPress admin dasbhoard, go to Appearance > Customize > Additional CSS. Paste the CSS there and click on publish.

You could edit colors that are in the CSS file.

Later I hope to make this process easier, maybe by adding inline styles.

### Other languages

I haven't explored that yet.

## Math

To be able to use math with MathJax, you'll need to customize your theme. 

From WordPress interface go to Appearance > Theme Editor. 
Add the lines below (that come from [MathJax docs](https://www.mathjax.org/#gettingstarted)) to the `<head>` div of `header.php`, then save.

```html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

Then refer to [the usage vignette](https://maelle.github.io/goodpress/articles/goodpress.html#math-with-mathjax).
