The summary is: create your posts in folders as index.Rmd with `hugodown::md_document` output format; knit, `wp_post()`, rinse, repeat.

* Create your posts in folders, one folder per post, with index.Rmd knitted to index.md and figures under a "figs" folder.

```{r}
fs::dir_tree(system.file(file.path("post-example2"), package = "goodpress"))
```

* The post index.Rmd should use [`hugodown::md_document`](https://hugodown.r-lib.org/reference/md_document.html) as an output format. 
* Knit your post and then, run the function `wp_post()` that takes the path **to the post folder** as argument, create a draft post in your website, uploads all image media stored in the "figs" folder, edits the references to image media and then publishes the post. 
* The first time you run `wp_post()` for a folder, it creates a file called `.wordpress.yml` in the post folder, that contains, in particular, the URL and ID of the post on your WordPress website. This way, next time the function is run, the post is _updated_.

[Example post](https://rmd-wordpress.eu/post-rmd/) and [its source](https://github.com/maelle/goodpress/tree/main/inst/post-example2). Note that it includes citations as footnotes by using the [same strategy as hugodown](https://github.com/r-lib/hugodown#citations).

### Author

You can either

* not write any author in the YAML metadata, and the author will be the authenticated user.
* write an existing username which is useful when you are posting or editing on someone else's behalf.

You cannot create an user with this package, you have to use WordPress interface for that.

### Publication status

The default status of the post is "publish". If you want another status (status has to be one of: "publish", "future", "draft", "pending", "private") , write it in the yaml (and then knit index.Rmd again) e.g.

```yaml
---
title: "Title of the Post"
date: "2020-04-01T00:00:00"
slug: "post-slug"
excerpt: "Here I summarize this fantastic post"
status: "private"
output: hugodown::md_document
---
```

The package cannot handle private posts with password, only private posts that are visible to admins and editors only. You could create a private post, and then from the WordPress interface make it visible with password. Make it private again before trying to update the post with the R package.

### Tags and categories

You can use tags and categories in the YAML metadata of index.Rmd (rendered to index.md). 
If a tag or a category doesn't exist `wp_post()` will create it for you.

e.g.

```yaml
---
title: "Title of the Post"
date: "2020-04-01T00:00:00"
slug: "post-slug"
excerpt: "Here I summarize this fantastic post"
status: "publish"
output: hugodown::md_document
categories:
  - math
  - code
tags:
  - crul
  - mathjax
  - R packages
---
```

Or (if there's a single category or single tag)

```yaml
---
title: "Another Rmd Blog Post"
date: "2020-04-01T00:00:00"
slug: "post-rmd"
excerpt: "Here I summarize this fantastic post"
output: hugodown::md_document
bibliography: refs.bib
suppress-bibliography: true
csl: chicago-fullnote-bibliography.csl
categories: R
tags:
  - citation
  - code
---
```

### Technical details

If you're curious. :-)

The "one post per folder" thing is inspired by Hugo leaf bundles. 

On disk your post is stored as index.Rmd and index.md, but before upload to the WordPress API it is transformed to HTML using [Pandoc](https://pandoc.org/).
